### ISSUE TITLE
[FEATURE] Implement a masking strategy for UPI VPAs

### ISSUE THREAD

**Issue by SanchithHegde** [juspay/hyperswitch#1578]
### Feature Description

Unified Payments Interface (UPI) is a popular payment technique in India, used to transfer money among individuals, bill payments and merchant payments. In the case of money transfer among individuals, users are identified with a Virtual Payment Address (VPA). A VPA is typically of the following format: `<identifier>@<bank_name>`. (Feel free to read up more about UPI if you aren't already familiar with it.)

Since a VPA can uniquely identify a user, we'd want to mask VPAs in our application. However, we'd want to keep the `<bank_name>` part unmasked, since it could help us build analytics on the banks or payment service providers used, and possibly improve our routing experience.

### Possible Implementation

We'd want you to implement `masking::Strategy` for UPI VPAs (which could be called `UpiVpaMaskingStrategy`) which masks the identifier completely, and keeps the bank name part in clear text. You can refer to the email masking strategy to get an idea of how this can be done. Please include unit tests for the same.

https://github.com/juspay/hyperswitch/blob/2f9c28938f95a58532604817b1ed370ef8285dd8/crates/common_utils/src/pii.rs#L190-L205

Also, update the type of `vpa_id` field in `api_models::payments::UpiData` to be `Option<Secret<String, UpiVpaMaskingStrategy>>` instead.

https://github.com/juspay/hyperswitch/blob/2f9c28938f95a58532604817b1ed370ef8285dd8/crates/api_models/src/payments.rs#L783-L786

**Comment by SargamPuram** [comment]
Hey ! I am a contributor in GSSOC'23.
I am interested to work on this issue . Just wanted to ensure is this the right approach , i am attaching some screenshots 
![juspay4](https://github.com/juspay/hyperswitch/assets/130867468/07d62043-2510-41bf-9cea-f7d36af5b48c)


As you have mentioned in the issue description I'll update it in api_models::payments::UpiData as well
![juspay2](https://github.com/juspay/hyperswitch/assets/130867468/339cad58-f54a-4b46-b24b-20e0593d94c9)
Is this okay . Because I am a beginner in Rust .
If you find the approach from the screenshots correct please can you assign me this issue . 
Also , I'll work on adding tests for it.

**Comment by SanchithHegde** [comment]
Hey @SargamPuram, thanks for your interest, I've assigned this to you.

Most of your code seems fine, there's a minor bug in your masking code however: the user identifier must be masked and the bank name must be unmasked, while your code does the opposite. Say the VPA is `my_name@upi`, we'd want the masked VPA to be `*******@upi`, while your current implementation would display it as `my_name@***`.

Feel free to open a PR once you've written the tests, we can continue this conversation and iterate over the code on the PR.

**Comment by SargamPuram** [comment]
Thanks for assigning me this issue . 
Sorry for the bug , I'll rectify it , add the tests and will create a PR . 
Thanks for explaining it in detail , because I'm new to Rust so , that could be the reason for this blunder . But I'll correct it for sure .
