### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sharmasagar33** [juspay/hyperswitch#2545]
### Bug Description

 In test mode, It has come to my attention that the system operates in the following manner: when a user tries to use an email address that already exists, the system sends a validation link to that email, allowing access to the website's dashboard. However, when a user attempts to use a random/ or unregistered someone's email, the system grants access to the dashboard without any validation.

### Expected Behavior

Needs to validate random email addresses for enhanced security and to prevent the creation of multiple fake accounts.

### Actual Behavior

In test mode, while login, when a user attempts to use a random/ or unregistered someone's email, the system grants access to the dashboard without any validation. 

### Steps To Reproduce

Provide an unambiguous set of steps to reproduce this bug. Include code or configuration to reproduce, if relevant.
1 Click on 'https://app.hyperswitch.io/login.'
2 Enter a random email address, such as "[reuhte@gmail.com], or any fake email like iewurhe@gmail.com or used others unregister mail.
3 You will be redirected inside the website, and you can access the dashboard without any validation or verification.

### Environment

1. Operating System : windows 10

### Have you spent some time checking if this bug has been raised before?

- [X] I checked and didn't find a similar issue

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/juspay/hyperswitch/blob/main/docs/CONTRIBUTING.md)

### Are you willing to submit a PR?

Yes, I am willing to submit a PR!

**Comment by ThisIsMani** [comment]
Hello @sharmasagar33, thank you for creating the issue. The current behaviour is intentional. When entering the dashboard for the first time, no email verification is required. However, if you attempt to log in to the same account again, email verification will be necessary. This doesn't impact security, as there is no data in the dashboard upon signup. This behaviour is also present in PayPal's sandbox account creation as well. This approach reduces friction during the sign-up process.

We plan to change this behaviour soon to include email verification during sign-up as well.
